"""Enum dạng hằng số để FE/BE dùng thống nhất."""

SESSION_TYPE_VEHICLE_WITH_PERSON = "VEHICLE_WITH_PERSON"
SESSION_TYPE_PERSON_ONLY = "PERSON_ONLY"

STATUS_WAITING_PERSON = "WAITING_PERSON"
STATUS_WAITING_VEHICLE = "WAITING_VEHICLE"
STATUS_WAITING_FACE_COMPARE = "WAITING_FACE_COMPARE"
STATUS_CHECKED_IN = "CHECKED_IN"
STATUS_CHECKED_OUT = "CHECKED_OUT"
STATUS_NEED_REVIEW = "NEED_REVIEW"
STATUS_REJECTED = "REJECTED"
STATUS_EXPIRED = "EXPIRED"

LINK_POLICY_ALLOW_VEHICLE_LINK = "ALLOW_VEHICLE_LINK"
LINK_POLICY_PERSON_ONLY_LOCKED = "PERSON_ONLY_LOCKED"

FACE_PENDING = "PENDING"
FACE_MATCH = "MATCH"
FACE_NO_MATCH = "NO_MATCH"
FACE_NEED_REVIEW = "NEED_REVIEW"


ACTIVE_SESSION_STATUSES = {
    STATUS_WAITING_PERSON,
    STATUS_WAITING_VEHICLE,
    STATUS_WAITING_FACE_COMPARE,
    STATUS_CHECKED_IN,
    STATUS_NEED_REVIEW,
}

FINAL_SESSION_STATUSES = {
    STATUS_CHECKED_OUT,
    STATUS_REJECTED,
    STATUS_EXPIRED,
}
